version: '3.3'

volumes:

  postgres:

services:

  postgres:
    image: postgres:13-alpine
    env_file: ./.env
    restart:  always
    ports:
      - ${POSTGRES_PORT?}:${POSTGRES_PORT?}
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./docker/web.dockerfile
    labels:
      - twenix
    env_file: ./.env
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    command:
      - ./docker/entrypoint.sh
